# Generated by Django 3.0.7 on 2020-07-31 08:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200727_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_street_address', models.CharField(max_length=100, null=True)),
                ('billing_street_address_line_2', models.CharField(max_length=100, null=True)),
                ('billing_city', models.CharField(max_length=100, null=True)),
                ('billing_phone_number', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('billing_postal_code', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('shipping_street_address', models.CharField(max_length=100, null=True)),
                ('shipping_street_address_line_2', models.CharField(max_length=100, null=True)),
                ('shipping_city', models.CharField(max_length=100, null=True)),
                ('shipping_phone_number', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('shipping_postal_code', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('shipping_is_billing', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CustomerAddresses',
            },
        ),
    ]
