# Generated by Django 3.0.7 on 2020-07-22 08:38

import datetime
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('city', models.TextField(default='Jalgaon')),
                ('phone_number', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('postal_code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='CompareItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('is_cmp', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref_number', models.CharField(max_length=15, null=True, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Use map widget for point the house location', srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Customer Locations',
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('is_fav', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MiniOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_of_vendor', models.CharField(max_length=15, null=True)),
                ('order_ref_number', models.CharField(default='ORD-100000', max_length=15)),
                ('mini_order_ref_number', models.CharField(default='MORN-100000', max_length=15, unique=True)),
                ('ordered_date', models.DateField()),
                ('ordered_time', models.TimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('Preparing Order', 'Preparing Order'), ('Shipping', 'Shipping'), ('Picked up from store', 'Picked up from store'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('RETURNED', 'RETURNED'), ('CANCELED', 'CANCELED')], default='Preparing Order', max_length=50)),
                ('received', models.BooleanField(blank=True, default=False, null=True)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref_number', models.CharField(default='ORD-100000', max_length=15, unique=True)),
                ('ordered_date', models.DateField()),
                ('ordered_time', models.TimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
                ('item_url', models.TextField(blank=True, default='', null=True)),
                ('order_status', models.CharField(choices=[('Preparing Order', 'Preparing Order'), ('Shipping', 'Shipping'), ('Picked up from store', 'Picked up from store'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('RETURNED', 'RETURNED'), ('CANCELED', 'CANCELED')], default='Preparing Order', max_length=50)),
                ('received', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_method', models.CharField(default='Online by card', max_length=30)),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('taxes', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 7, 22, 8, 38, 43, 665487, tzinfo=utc))),
                ('title', models.CharField(max_length=300)),
                ('review_description', models.TextField()),
                ('rating', models.CharField(choices=[('1', 'Terrible'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=1)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption1', models.CharField(max_length=100)),
                ('caption2', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='Size: 1920x570', upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('one_click_purchasing', models.BooleanField(default=False)),
            ],
        ),
    ]
