# Generated by Django 3.0.7 on 2020-07-24 09:23

import datetime
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('city', models.TextField(default='Jalgaon')),
                ('phone_number', models.BigIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('postal_code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_date', models.DateTimeField(default=datetime.datetime(2020, 7, 24, 9, 23, 49, 933533, tzinfo=utc))),
                ('cancel_reason', models.CharField(choices=[('', ''), ('Not Needed', 'Not Needed'), ('Ordered Wrong Product', 'Ordered Wrong Product'), ('Receiving To Late', 'Receiving To Late'), ('Select Different Payment Method', 'Select Different Payment Method'), ('Other', 'Other')], default='', max_length=50)),
                ('request_cancel_type', models.CharField(choices=[('CANCEL', 'CANCEL'), ('Exchange', 'Exchange')], default='CANCEL', max_length=50)),
                ('review_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompareItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('is_cmp', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('discount_percent', models.FloatField()),
                ('minimum_order_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CouponCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('discount_amount', models.FloatField(null=True)),
                ('order_amount', models.FloatField(null=True)),
                ('used', models.BooleanField(default=False)),
                ('applicable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref_number', models.CharField(max_length=15, null=True, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Use map widget for point the house location', srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Customer Locations',
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('is_fav', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MiniOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref_number', models.CharField(default='ORD-100000', max_length=15)),
                ('mini_order_ref_number', models.CharField(default='MORN-100000', max_length=15, unique=True)),
                ('ordered_date', models.DateField()),
                ('ordered_time', models.TimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('Preparing Order', 'Preparing Order'), ('Shipping', 'Shipping'), ('Picked up from store', 'Picked up from store'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('RETURNED', 'RETURNED'), ('CANCELED', 'CANCELED')], default='Preparing Order', max_length=50)),
                ('delivered', models.BooleanField(blank=True, default=False, null=True)),
                ('return_requested', models.BooleanField(default=False)),
                ('return_granted', models.BooleanField(default=False)),
                ('return_window', models.DateTimeField(default=datetime.datetime(2020, 8, 3, 9, 23, 49, 928546, tzinfo=utc))),
                ('return_status', models.CharField(choices=[('', ''), ('Return Denied', 'Return Denied'), ('Processing Return Request', 'Processing Return Request'), ('Item Picked up', 'Item Picked up '), ('Item Received Vendor', 'Item Received Vendor'), ('Return Granted', 'Return Granted'), ('CANCELED', 'CANCELED')], default='', max_length=50)),
                ('cancel_status', models.CharField(choices=[('', ''), ('CANCEL Denied', 'CANCEL Denied'), ('Processing Cancel Request', 'Processing Cancel Request'), ('Cancel Granted', 'Cancel Granted')], default='', max_length=50)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('cancel_granted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref_number', models.CharField(default='ORD-100000', max_length=15, unique=True)),
                ('ordered_date', models.DateField()),
                ('ordered_time', models.TimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('item_url', models.TextField(blank=True, default='', null=True)),
                ('received', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_method', models.CharField(default='Online by card', max_length=30)),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('taxes', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(default=datetime.datetime(2020, 7, 24, 9, 23, 49, 932535, tzinfo=utc))),
                ('return_reason', models.CharField(choices=[('', ''), ('Not as Describe', 'Not as Describe'), ('Damaged', 'Damaged'), ('Expired', 'Expired'), ('Ordered Wrong Item', 'Ordered Wrong Item'), ('Received Wrong Item', 'Received Wrong Item'), ('Received Wrong Brand Item', 'Received Wrong Brand Item'), ('Other', 'Other')], default='', max_length=50)),
                ('request_return_type', models.CharField(choices=[('RETURN', 'RETURN'), ('Exchange', 'Exchange')], default='RETURN', max_length=50)),
                ('review_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 7, 24, 9, 23, 49, 932535, tzinfo=utc))),
                ('title', models.CharField(max_length=300)),
                ('review_description', models.TextField()),
                ('rating', models.CharField(choices=[('1', 'Terrible'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=1)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption1', models.CharField(max_length=100)),
                ('caption2', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='Size: 1920x570', upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('one_click_purchasing', models.BooleanField(default=False)),
            ],
        ),
    ]
