# Generated by Django 3.0.7 on 2020-07-17 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200717_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 15, 34, 48, 965333, tzinfo=utc)),
        ),
    ]
