# Generated by Django 3.0.7 on 2020-07-24 09:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_auto_20200724_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel',
            name='cancel_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 9, 51, 10, 269690, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='miniorder',
            name='return_window',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 9, 51, 10, 265701, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 9, 51, 10, 268693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 9, 51, 10, 268693, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PrescriptionUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
