# Generated by Django 3.0.7 on 2020-07-22 08:51

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200722_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresss',
            name='phone_number',
            field=models.BigIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 8, 51, 31, 297858, tzinfo=utc)),
        ),
    ]
