# Generated by Django 3.0.7 on 2020-07-26 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200726_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel',
            name='cancel_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 7, 28, 11, 823787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='miniorder',
            name='return_window',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 7, 28, 11, 819820, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 7, 28, 11, 823787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 7, 28, 11, 822795, tzinfo=utc)),
        ),
    ]
