# Generated by Django 3.0.7 on 2020-07-17 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200717_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 15, 49, 37, 188277, tzinfo=utc)),
        ),
    ]
