# Generated by Django 3.0.7 on 2020-07-22 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200722_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 9, 38, 42, 458685, tzinfo=utc)),
        ),
    ]
