# Generated by Django 3.0.7 on 2020-07-26 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200726_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel',
            name='cancel_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 8, 49, 48, 955472, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='miniorder',
            name='return_window',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 8, 49, 48, 951503, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 8, 49, 48, 955472, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 8, 49, 48, 954478, tzinfo=utc)),
        ),
    ]
