# Generated by Django 3.0.7 on 2020-07-26 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200726_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel',
            name='cancel_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 11, 42, 21, 475944, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='miniorder',
            name='return_window',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 11, 42, 21, 470984, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 11, 42, 21, 474952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 11, 42, 21, 474952, tzinfo=utc)),
        ),
    ]
