# Generated by Django 3.0.7 on 2020-07-22 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200722_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('', ''), ('Return Requested', 'Return Requested'), ('Processing Return Request', 'Processing Return Request'), ('Item Picked up', 'Item Picked up '), ('Item Received Vendor', 'Item Received Vendor'), ('Return Accepted', 'Return Accepted'), ('CANCELED', 'CANCELED')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='return_window',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 12, 43, 31, 918467, tzinfo=utc), editable=False),
        ),
    ]
