# Generated by Django 3.0.7 on 2020-07-22 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200722_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_window',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 18, 14, 54, 982711)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 12, 44, 54, 985686, tzinfo=utc), editable=False),
        ),
    ]
