# Generated by Django 3.0.7 on 2020-07-22 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200722_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miniorder',
            old_name='refund_granted',
            new_name='return_granted',
        ),
        migrations.RenameField(
            model_name='miniorder',
            old_name='refund_requested',
            new_name='return_requested',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_window',
        ),
        migrations.AddField(
            model_name='miniorder',
            name='return_status',
            field=models.CharField(choices=[('', ''), ('Return Requested', 'Return Requested'), ('Processing Return Request', 'Processing Return Request'), ('Item Picked up', 'Item Picked up '), ('Item Received Vendor', 'Item Received Vendor'), ('Return Accepted', 'Return Accepted'), ('CANCELED', 'CANCELED')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='miniorder',
            name='return_window',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 18, 20, 29, 67948)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 18, 20, 29, 70898), editable=False),
        ),
    ]
