# Generated by Django 3.0.7 on 2020-07-19 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200719_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='order_ref_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 10, 47, 58, 871999, tzinfo=utc)),
        ),
    ]
