# Generated by Django 3.0.7 on 2020-07-19 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('store', '0010_auto_20200719_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 12, 47, 49, 852893, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='MiniOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref_number', models.CharField(default='ORD-100000', max_length=15)),
                ('mini_order_ref_number', models.CharField(default='MORD-100000', max_length=15, unique=True)),
                ('ordered_date', models.DateField()),
                ('ordered_time', models.TimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('Preparing Order', 'Preparing Order'), ('Shipping', 'Shipping'), ('Picked up from store', 'Picked up from store'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('RETURNED', 'RETURNED'), ('CANCELED', 'CANCELED')], default='Preparing Order', max_length=50)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.OrderItem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='mini_order',
            field=models.ManyToManyField(to='store.MiniOrder'),
        ),
    ]
