# Generated by Django 3.0.7 on 2020-07-22 13:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_auto_20200722_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniorder',
            name='return_window',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 19, 1, 21, 62846)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 19, 1, 21, 69792), editable=False),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(default=datetime.datetime(2020, 7, 22, 19, 1, 21, 70784))),
                ('return_reason', models.CharField(choices=[('', ''), ('Not as Describe', 'Not as Describe'), ('Damaged', 'Damaged'), ('Expired', 'Expired'), ('Ordered Wrong Item', 'Ordered Wrong Item'), ('Received Wrong Item', 'Received Wrong Item'), ('Received Wrong Brand Item', 'Received Wrong Brand Item'), ('Other', 'Other')], default='Not as Describe', max_length=50)),
                ('request_return_type', models.CharField(choices=[('RETURN', 'RETURN'), ('Exchange', 'Exchange')], default='RETURN', max_length=50)),
                ('review_description', models.TextField()),
                ('mini_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.MiniOrder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
