# Generated by Django 3.0.7 on 2020-07-19 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200719_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniorder',
            name='mini_order_ref_number',
            field=models.CharField(default='MORN-100000', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 12, 54, 7, 185074, tzinfo=utc)),
        ),
    ]
