# Generated by Django 3.0.7 on 2020-07-19 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20200719_2057'),
        ('store', '0012_auto_20200719_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 15, 27, 11, 576663, tzinfo=utc)),
        ),
    ]
