# Generated by Django 3.0.7 on 2020-07-22 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200722_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniorder',
            name='return_window',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 13, 40, 52, 572918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 13, 40, 52, 576885, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 19, 10, 52, 576885), editable=False),
        ),
    ]
