# Generated by Django 3.0.7 on 2020-07-27 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200727_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniorder',
            name='return_window',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
