# Generated by Django 3.0.7 on 2020-07-19 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200719_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 15, 32, 27, 764999, tzinfo=utc)),
        ),
    ]
