# Generated by Django 3.0.7 on 2020-07-22 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200722_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniorder',
            name='item_of_vendor',
        ),
        migrations.AlterField(
            model_name='miniorder',
            name='return_status',
            field=models.CharField(choices=[('', ''), ('Return Denied', 'Return Denied'), ('Processing Return Request', 'Processing Return Request'), ('Item Picked up', 'Item Picked up '), ('Item Received Vendor', 'Item Received Vendor'), ('Return Accepted', 'Return Accepted'), ('CANCELED', 'CANCELED')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='miniorder',
            name='return_window',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 13, 58, 57, 57151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 13, 58, 57, 61119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 13, 58, 57, 60127, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
