# Generated by Django 3.0.7 on 2020-07-22 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20200722_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miniorder',
            old_name='received',
            new_name='delivered',
        ),
        migrations.AlterField(
            model_name='miniorder',
            name='return_window',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 16, 27, 41, 373019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 16, 27, 41, 379962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 16, 27, 41, 378970, tzinfo=utc)),
        ),
    ]
