# Generated by Django 3.0.7 on 2020-07-23 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20200722_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniorder',
            name='cancel_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miniorder',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='miniorder',
            name='return_status',
            field=models.CharField(choices=[('', ''), ('Return Denied', 'Return Denied'), ('Processing Return Request', 'Processing Return Request'), ('Item Picked up', 'Item Picked up '), ('Item Received Vendor', 'Item Received Vendor'), ('Return Granted', 'Return Granted'), ('CANCELED', 'CANCELED')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='miniorder',
            name='return_window',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 11, 43, 48, 3381, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 11, 43, 48, 8341, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 11, 43, 48, 7349, tzinfo=utc)),
        ),
    ]
