# Generated by Django 3.0.7 on 2020-08-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='caption1',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='caption2',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='link',
        ),
        migrations.DeleteModel(
            name='Addresss',
        ),
    ]
