# Generated by Django 3.0.7 on 2020-07-23 12:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0019_auto_20200723_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniorder',
            name='cancel_status',
            field=models.CharField(choices=[('', ''), ('CANCEL Denied', 'CANCEL Denied'), ('Processing Cancel Request', 'Processing Cancel Request'), ('Cancel Granted', 'Return Granted')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='miniorder',
            name='return_window',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 12, 47, 56, 292941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 12, 47, 56, 296909, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_reason',
            field=models.CharField(choices=[('', ''), ('Not as Describe', 'Not as Describe'), ('Damaged', 'Damaged'), ('Expired', 'Expired'), ('Ordered Wrong Item', 'Ordered Wrong Item'), ('Received Wrong Item', 'Received Wrong Item'), ('Received Wrong Brand Item', 'Received Wrong Brand Item'), ('Other', 'Other')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 12, 47, 56, 295917, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_date', models.DateTimeField(default=datetime.datetime(2020, 7, 23, 12, 47, 56, 296909, tzinfo=utc))),
                ('cancel_reason', models.CharField(choices=[('', ''), ('Not Needed', 'Not Needed'), ('Ordered Wrong Product', 'Ordered Wrong Product'), ('Receiving To Late', 'Receiving To Late'), ('Select Different Payment Method', 'Select Different Payment Method'), ('Other', 'Other')], default='', max_length=50)),
                ('request_cancel_type', models.CharField(choices=[('CANCEL', 'CANCEL'), ('Exchange', 'Exchange')], default='CANCEL', max_length=50)),
                ('review_description', models.TextField(null=True)),
                ('mini_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.MiniOrder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
