# Generated by Django 3.0.7 on 2020-07-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ref_number', models.CharField(default='IRN-100000', max_length=15, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(choices=[('Sale', 'Sale'), ('New', 'New'), ('Promotion', 'Promotion'), ('Trending', 'Trending'), ('Top Selling', 'Top Selling')], max_length=11, null=True)),
                ('slug', models.SlugField()),
                ('stock_no', models.IntegerField()),
                ('short_description', models.TextField(help_text='To describe product in short', null=True)),
                ('description', models.TextField(help_text='Overview product', null=True)),
                ('key_benefits', models.TextField(help_text="Describe product's Benefits", null=True)),
                ('direction_for_use', models.TextField(help_text="Describe product's Direction for use / Dosage", null=True)),
                ('safety_information', models.TextField(help_text="Describe product's Safety information", null=True)),
                ('image_main', models.ImageField(null=True, upload_to='')),
                ('image_2', models.ImageField(null=True, upload_to='')),
                ('image_3', models.ImageField(null=True, upload_to='')),
                ('image_4', models.ImageField(null=True, upload_to='')),
                ('image_5', models.ImageField(null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('trending', models.BooleanField(default=False)),
                ('has_variation', models.BooleanField(default=False, help_text='If this is ticked, You can add variation later to this product.')),
                ('variation_id', models.CharField(max_length=20, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.Brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.Category')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Vendor')),
            ],
        ),
    ]
