# Generated by Django 3.0.7 on 2020-07-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
