# Generated by Django 3.0.7 on 2020-08-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
