# Generated by Django 3.0.7 on 2020-07-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='image',
            new_name='brand_image',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='name',
            new_name='brand_name',
        ),
    ]
