# Generated by Django 3.0.7 on 2020-07-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20200717_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
