# Generated by Django 3.0.7 on 2020-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20200722_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sameitem',
            name='stock_no',
            field=models.IntegerField(null=True),
        ),
    ]
