# Generated by Django 3.0.7 on 2020-08-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_item_total_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='total_stock',
            field=models.IntegerField(null=True),
        ),
    ]
