# Generated by Django 3.0.7 on 2020-07-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20200722_1508'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sameitem',
            unique_together={('item_ref_number', 'vendor')},
        ),
    ]
