# Generated by Django 3.0.7 on 2020-07-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20200717_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
