# Generated by Django 3.0.7 on 2020-07-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20200719_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='VendorLocation',
        ),
    ]
