# Generated by Django 3.0.7 on 2020-07-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20200719_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorlocation',
            name='order_ref_number',
        ),
        migrations.AddField(
            model_name='vendorlocation',
            name='vendor_ref_id',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
